"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var apee_router_1 = require("apee-router");
var template_1 = require("./template");
var get_1 = require("./route/get");
var router = new apee_router_1.Router();
(0, template_1.loadTemplate)(router);
router.set(['home', 'search', 'login', 'user', 'add', 'get']);
router.set('get', get_1.routeGet);
router.start();
